name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

run-name: Release ${{ github.ref_name }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create release
      run: gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "gitter"
        release_tag: ${{ github.ref_name }}
        ldflags: -X "github.com/kloudyuk/gitter/cmd.Version=${{ github.ref_name }}" -X "github.com/kloudyuk/gitter/cmd.SHA=${{ github.sha }}"
