name: Release

on:
  release:
    types: [created]

run-name: Release ${{ github.ref_name }}

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "gitter"
        release_tag: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        ldflags: -X "github.com/kloudyuk/gitter/cmd.Version=${{ github.ref_name }}" -X "github.com/kloudyuk/gitter/cmd.SHA=${{ github.sha }}"
